import { FitnessAIProvider, FitnessContext, CoachResponse } from "./provider";

/**
 * Gemini Provider for SAI FITNESS OS
 * 
 * This is a shell implementation ready to be connected to the Gemini API.
 * For now, it delegates to the local-coach or returns a placeholder if called directly,
 * but the interface is strictly defined.
 */
export class GeminiProvider implements FitnessAIProvider {
  name = "Gemini Pro Fitness Analyst";
  private apiKey: string | null = null;

  constructor(apiKey?: string) {
    // Check local storage or env for API key in a real implementation
    if (typeof window !== "undefined") {
      this.apiKey = localStorage.getItem("sai_gemini_api_key") || apiKey || null;
    } else {
      this.apiKey = apiKey || process.env.NEXT_PUBLIC_GEMINI_API_KEY || null;
    }
  }

  async isAvailable(): Promise<boolean> {
    // Return true if we have a valid API key configured
    return !!this.apiKey;
  }

  private buildSystemPrompt(context: FitnessContext): string {
    return `
      You are SAI COACH, a premium personal performance analyst and fitness coach.
      Do not fabricate information. Use only the provided context.
      
      User Profile: ${JSON.stringify(context.profile, null, 2)}
      Week: ${context.currentWeek}, Phase: ${context.currentPhase}
      
      You must respond in a specific JSON format matching the CoachResponse interface:
      {
        "answer": "Direct answer to the user's question",
        "reasoning": "The 'Why Layer' explaining the scientific or logical reasoning behind the answer",
        "confidence": "high|medium|low|insufficient-data",
        "source": "ai",
        "suggestions": ["Follow-up suggestion 1", "Follow-up suggestion 2"]
      }
    `;
  }

  async askCoach(question: string, context: FitnessContext): Promise<CoachResponse> {
    if (!this.apiKey) {
      throw new Error("Gemini API key not configured");
    }

    // Placeholder for actual fetch to Gemini API
    // const response = await fetch("https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent", ...)
    
    return {
      answer: "This is a placeholder response from the Gemini Provider shell. The API integration is ready to be wired up.",
      reasoning: "API key is configured, but the actual fetch call is stubbed out for Phase 3 readiness.",
      confidence: "high",
      source: "ai",
      suggestions: ["Connect a real Gemini API endpoint"],
    };
  }

  async generateWeeklyReview(context: FitnessContext): Promise<CoachResponse> {
    if (!this.apiKey) throw new Error("Gemini API key not configured");
    
    return {
      answer: "Your weekly review generated by Gemini will appear here.",
      reasoning: "Analyzed all 7 days of training and nutrition data.",
      confidence: "high",
      source: "ai",
      suggestions: ["View detailed analytics"],
    };
  }

  async generateDailySummary(context: FitnessContext): Promise<CoachResponse> {
    if (!this.apiKey) throw new Error("Gemini API key not configured");
    
    return {
      answer: "Your daily summary generated by Gemini will appear here.",
      reasoning: "Analyzed today's readiness and planned workouts.",
      confidence: "high",
      source: "ai",
    };
  }
}
